import { PublicPageLayout } from "./PublicPageLayout";

const ProviderList = () => <ul><li><strong>Supabase</strong> provides account authentication and the application database.</li><li><strong>Vercel</strong> provides web hosting and may process operational request logs.</li><li><strong>OpenStreetMap-based map tiles and Nominatim search</strong> help display maps and resolve place searches. Requests to these services may include technical information such as IP address under their own policies.</li></ul>;

export function Privacy() {
  return <PublicPageLayout eyebrow="Working policy draft" title={<>Privacy, with a clear <em>route.</em></>} intro="Last updated 14 August 2026. This is a plain-language working draft for FocusFlight and must be reviewed by qualified legal counsel before it is relied upon as final legal policy.">
    <article className="legal-document"><div className="legal-callout"><strong>Important:</strong> FocusFlight is a virtual focus-timer project. Selected airports, routes, and current locations in the app are virtual focus data, not physical-location tracking or real travel records.</div><h2>What this draft covers</h2><p>This draft explains how FocusFlight currently processes information when someone creates an account, completes a virtual focus flight, uses maps or search, joins a Co-Focus room, uses profile and ranking controls, or sends feedback. FocusFlight does not sell personal information.</p><h2>Information processed</h2><p>FocusFlight processes account email and authentication session data, profile fields supplied by the user, virtual route and completed-session records, group-room and social relationship data, ranking participation choices, feedback submissions, and necessary technical or hosting logs.</p><h2>Why information is used</h2><p>The information is used to operate accounts, save personal and group focus history, display privacy-selected profile information, provide map and timer features, maintain room and ranking features, receive feedback, and keep the service reliable and secure.</p><h2>Service providers</h2><ProviderList /><h2>Visibility and controls</h2><p>Profile visibility, virtual current-location visibility, leaderboard participation, and friendship or blocking actions are controlled in the product. Solo and Co-Focus history are separate. Blocking takes priority over social access. FocusFlight does not intentionally expose private trip records through public profile or ranking pages.</p><h2>Feedback and retention</h2><p>Feedback is submitted by signed-in users and stored privately for product improvement. The current product does not yet offer an in-app account deletion workflow. Until that process is implemented, a signed-in user may use the Feedback page to request account or data help. Retention periods and deletion handling must be confirmed before this draft becomes final.</p><h2>Security and updates</h2><p>FocusFlight uses reasonable technical measures intended to protect data, but no online service can promise absolute security. This policy will be updated when the product, providers, data handling, or legal requirements change. Material updates should carry a new date and clear notice.</p></article>
  </PublicPageLayout>;
}

export function Terms() {
  return <PublicPageLayout eyebrow="Working terms draft" title={<>Terms for a virtual <em>journey.</em></>} intro="Last updated 14 August 2026. This working draft describes the current product and requires qualified legal review before it is relied upon as final terms of service.">
    <article className="legal-document"><div className="legal-callout"><strong>Virtual by design:</strong> FocusFlight is not a flight booking, navigation, aviation, or real-world travel service. Routes, durations, locations, and journey records are part of a virtual productivity experience.</div><h2>Using FocusFlight</h2><p>FocusFlight is a virtual focus-timer web application. By using it, you agree to use the service lawfully and responsibly, keep account information reasonably accurate, protect account access, and follow applicable rules when interacting with other people through rooms or profiles.</p><h2>Acceptable use</h2><p>You must not abuse or interfere with the service, attempt unauthorized access to accounts or data, use prohibited automation, submit fraudulent information, harass others, evade blocking controls, or use Co-Focus rooms and profiles to cause harm.</p><h2>Accounts, virtual flights, and feedback</h2><p>Users are responsible for their account activity. Completed routes and virtual current locations represent focus sessions, not physical presence. If you submit feedback, you permit the project to use the ideas to improve FocusFlight without compensation; personal information in feedback remains subject to the Privacy draft.</p><h2>Availability and change</h2><p>FocusFlight may change, pause, or discontinue features as the project evolves. The service is provided without a guarantee of uninterrupted availability, route-data accuracy for real-world aviation, or suitability for every use case.</p><h2>Intellectual property</h2><p>The FocusFlight name, design, product content, and software are protected as applicable. Users retain rights in information they supply, subject to the permissions needed to operate the service.</p><h2>Suspension, updates, and contact</h2><p>Accounts or access may be restricted when necessary to address misuse, security risks, legal requirements, or service operation. Terms may be updated as the product changes. Governing law, dispute terms, and a final legal contact method will be added only after the operator’s jurisdiction and legal advice are established.</p></article>
  </PublicPageLayout>;
}
